### ISSUE TITLE
Map has points on wrong locations

### ISSUE THREAD

**Issue by mikaelmello** [RocketChat/rocketchat.github.io#631]
![image](https://user-images.githubusercontent.com/17488630/51393459-e5ce9280-1b1e-11e9-850c-be6e2652d331.png)

**Comment by Rodriq** [comment]
Hey @mikaelmello  I found out that is issue might have been resolved as seen here.
=> [Contact Page](https://rocket.chat/contact)
So @Sing-Li @rodrigok  or anyone I think this issue should be closed. This will help keep the repo organised.

![image](https://user-images.githubusercontent.com/39289592/52563489-d848b780-2e01-11e9-9fb5-e5331d938e3a.png)

**Comment by mikaelmello** [comment]
@Rodriq, no, sorry, still broken here:

Firefox Dev Edition 66.0b5 (64-bit)

![image](https://user-images.githubusercontent.com/17488630/52564288-f0f9a300-2dea-11e9-8a25-b89b284fd107.png)

**Comment by mikaelmello** [comment]
By the way, it is also a bit broken in your image, it is harder to notice but London for example is on the wrong place.

**Comment by Rodriq** [comment]
okay @mikaelmello  Maybe shows that large difference because of either your screen resolution or the browser like stated.

**Comment by Rodriq** [comment]
Hey @mikaelmello please can you give me the dimension of your screen?
 I'd be of great help.

**Comment by mikaelmello** [comment]
Hello!

This picture is from a 1920x1080 screen, previous ones were taken on a 4K resolution (but Chrome and Firefox render pages with a smaller resolution, I don't remember the number exactly)

![image](https://user-images.githubusercontent.com/17488630/53813473-809ef700-3f3c-11e9-9187-cfa4a190d5f5.png)

**Comment by Rodriq** [comment]
I don't know why @mikaelmello they seem to have remove that point.
